/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct img_in {
	struct {
		u_int input_len;
		char *input_val;
	} input;
};
typedef struct img_in img_in;

struct img_out {
	struct {
		u_int output_len;
		char *output_val;
	} output;
};
typedef struct img_out img_out;

#define MINIFYJPEG_PROG 0x31234567
#define MINIFYJPEG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFYJPEG_PROC 1
extern  enum clnt_stat minifyjpeg_proc_1(img_in , img_out *, CLIENT *);
extern  bool_t minifyjpeg_proc_1_svc(img_in , img_out *, struct svc_req *);
extern int minifyjpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFYJPEG_PROC 1
extern  enum clnt_stat minifyjpeg_proc_1();
extern  bool_t minifyjpeg_proc_1_svc();
extern int minifyjpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_img_in (XDR *, img_in*);
extern  bool_t xdr_img_out (XDR *, img_out*);

#else /* K&R C */
extern bool_t xdr_img_in ();
extern bool_t xdr_img_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
